language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt.txt

script:
  - python -m unittest tests/multiplication_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDlkNDIyYzhmLTQyNzQtNGVhNi04MjY4LTFjZDE4MzM3ZjA0NAACRHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJweXRob24tcmFtemluZXgtYXBpIl19LCAidmVyc2lvbiI6IDF9AAAGIOKRGxvmK6vBdqC1x75SX9PnSbuqMiI3HGSOdMRuaIDw"
  on:
    branch: master